### Find all posts in database.
GET http://localhost:8080/api/v1/posts

### Find a single post by id
GET http://localhost:8080/api/v1/posts/1

### Create a new post
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "content": "Post 1"
}

### Get all replies for a post by id
GET http://localhost:8080/api/v1/posts/1/replies

### Get a single reply for a post by id
GET http://localhost:8080/api/v1/posts/1/replies/2